// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange.proto

package com.qianxun.model;

public final class BaseExchangeProtos {
  private BaseExchangeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.qianxun.model.BaseExchangeProtos.RoseExchange.roseExchange);
    registry.add(com.qianxun.model.BaseExchangeProtos.GemExchange.gemExchange);
  }
  public interface BaseExchangeOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<BaseExchange> {

    // required string type = 1;
    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.qianxun.model.BaseExchange}
   */
  public static final class BaseExchange extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        BaseExchange> implements BaseExchangeOrBuilder {
    // Use BaseExchange.newBuilder() to construct.
    private BaseExchange(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.qianxun.model.BaseExchangeProtos.BaseExchange, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseExchange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseExchange defaultInstance;
    public static BaseExchange getDefaultInstance() {
      return defaultInstance;
    }

    public BaseExchange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_BaseExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_BaseExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianxun.model.BaseExchangeProtos.BaseExchange.class, com.qianxun.model.BaseExchangeProtos.BaseExchange.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseExchange> PARSER =
        new com.google.protobuf.AbstractParser<BaseExchange>() {
      public BaseExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseExchange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseExchange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.qianxun.model.BaseExchangeProtos.BaseExchange>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.BaseExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qianxun.model.BaseExchangeProtos.BaseExchange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qianxun.model.BaseExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.qianxun.model.BaseExchangeProtos.BaseExchange, Builder> implements com.qianxun.model.BaseExchangeProtos.BaseExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_BaseExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_BaseExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianxun.model.BaseExchangeProtos.BaseExchange.class, com.qianxun.model.BaseExchangeProtos.BaseExchange.Builder.class);
      }

      // Construct using com.qianxun.model.BaseExchangeProtos.BaseExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_BaseExchange_descriptor;
      }

      public com.qianxun.model.BaseExchangeProtos.BaseExchange getDefaultInstanceForType() {
        return com.qianxun.model.BaseExchangeProtos.BaseExchange.getDefaultInstance();
      }

      public com.qianxun.model.BaseExchangeProtos.BaseExchange build() {
        com.qianxun.model.BaseExchangeProtos.BaseExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianxun.model.BaseExchangeProtos.BaseExchange buildPartial() {
        com.qianxun.model.BaseExchangeProtos.BaseExchange result = new com.qianxun.model.BaseExchangeProtos.BaseExchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianxun.model.BaseExchangeProtos.BaseExchange) {
          return mergeFrom((com.qianxun.model.BaseExchangeProtos.BaseExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianxun.model.BaseExchangeProtos.BaseExchange other) {
        if (other == com.qianxun.model.BaseExchangeProtos.BaseExchange.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianxun.model.BaseExchangeProtos.BaseExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianxun.model.BaseExchangeProtos.BaseExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string type = 1;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qianxun.model.BaseExchange)
    }

    static {
      defaultInstance = new BaseExchange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qianxun.model.BaseExchange)
  }

  public interface RoseExchangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 uid = 1;
    /**
     * <code>required int64 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     */
    long getUid();

    // optional int32 count = 2;
    /**
     * <code>optional int32 count = 2;</code>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 2;</code>
     */
    int getCount();

    // required string trend = 3;
    /**
     * <code>required string trend = 3;</code>
     */
    boolean hasTrend();
    /**
     * <code>required string trend = 3;</code>
     */
    java.lang.String getTrend();
    /**
     * <code>required string trend = 3;</code>
     */
    com.google.protobuf.ByteString
        getTrendBytes();

    // required string discription = 4;
    /**
     * <code>required string discription = 4;</code>
     */
    boolean hasDiscription();
    /**
     * <code>required string discription = 4;</code>
     */
    java.lang.String getDiscription();
    /**
     * <code>required string discription = 4;</code>
     */
    com.google.protobuf.ByteString
        getDiscriptionBytes();
  }
  /**
   * Protobuf type {@code com.qianxun.model.RoseExchange}
   */
  public static final class RoseExchange extends
      com.google.protobuf.GeneratedMessage
      implements RoseExchangeOrBuilder {
    // Use RoseExchange.newBuilder() to construct.
    private RoseExchange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoseExchange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoseExchange defaultInstance;
    public static RoseExchange getDefaultInstance() {
      return defaultInstance;
    }

    public RoseExchange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoseExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              trend_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              discription_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_RoseExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_RoseExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianxun.model.BaseExchangeProtos.RoseExchange.class, com.qianxun.model.BaseExchangeProtos.RoseExchange.Builder.class);
    }

    public static com.google.protobuf.Parser<RoseExchange> PARSER =
        new com.google.protobuf.AbstractParser<RoseExchange>() {
      public RoseExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoseExchange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoseExchange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    // optional int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    // required string trend = 3;
    public static final int TREND_FIELD_NUMBER = 3;
    private java.lang.Object trend_;
    /**
     * <code>required string trend = 3;</code>
     */
    public boolean hasTrend() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string trend = 3;</code>
     */
    public java.lang.String getTrend() {
      java.lang.Object ref = trend_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trend_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string trend = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTrendBytes() {
      java.lang.Object ref = trend_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string discription = 4;
    public static final int DISCRIPTION_FIELD_NUMBER = 4;
    private java.lang.Object discription_;
    /**
     * <code>required string discription = 4;</code>
     */
    public boolean hasDiscription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string discription = 4;</code>
     */
    public java.lang.String getDiscription() {
      java.lang.Object ref = discription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          discription_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string discription = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDiscriptionBytes() {
      java.lang.Object ref = discription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uid_ = 0L;
      count_ = 0;
      trend_ = "";
      discription_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrend()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDiscription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTrendBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDiscriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTrendBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDiscriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.RoseExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qianxun.model.BaseExchangeProtos.RoseExchange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qianxun.model.RoseExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qianxun.model.BaseExchangeProtos.RoseExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_RoseExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_RoseExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianxun.model.BaseExchangeProtos.RoseExchange.class, com.qianxun.model.BaseExchangeProtos.RoseExchange.Builder.class);
      }

      // Construct using com.qianxun.model.BaseExchangeProtos.RoseExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        trend_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        discription_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_RoseExchange_descriptor;
      }

      public com.qianxun.model.BaseExchangeProtos.RoseExchange getDefaultInstanceForType() {
        return com.qianxun.model.BaseExchangeProtos.RoseExchange.getDefaultInstance();
      }

      public com.qianxun.model.BaseExchangeProtos.RoseExchange build() {
        com.qianxun.model.BaseExchangeProtos.RoseExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianxun.model.BaseExchangeProtos.RoseExchange buildPartial() {
        com.qianxun.model.BaseExchangeProtos.RoseExchange result = new com.qianxun.model.BaseExchangeProtos.RoseExchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.trend_ = trend_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.discription_ = discription_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianxun.model.BaseExchangeProtos.RoseExchange) {
          return mergeFrom((com.qianxun.model.BaseExchangeProtos.RoseExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianxun.model.BaseExchangeProtos.RoseExchange other) {
        if (other == com.qianxun.model.BaseExchangeProtos.RoseExchange.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasTrend()) {
          bitField0_ |= 0x00000004;
          trend_ = other.trend_;
          onChanged();
        }
        if (other.hasDiscription()) {
          bitField0_ |= 0x00000008;
          discription_ = other.discription_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasTrend()) {
          
          return false;
        }
        if (!hasDiscription()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianxun.model.BaseExchangeProtos.RoseExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianxun.model.BaseExchangeProtos.RoseExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 uid = 1;
      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 count = 2;
      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      // required string trend = 3;
      private java.lang.Object trend_ = "";
      /**
       * <code>required string trend = 3;</code>
       */
      public boolean hasTrend() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public java.lang.String getTrend() {
        java.lang.Object ref = trend_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          trend_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTrendBytes() {
        java.lang.Object ref = trend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public Builder setTrend(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        trend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public Builder clearTrend() {
        bitField0_ = (bitField0_ & ~0x00000004);
        trend_ = getDefaultInstance().getTrend();
        onChanged();
        return this;
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public Builder setTrendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        trend_ = value;
        onChanged();
        return this;
      }

      // required string discription = 4;
      private java.lang.Object discription_ = "";
      /**
       * <code>required string discription = 4;</code>
       */
      public boolean hasDiscription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public java.lang.String getDiscription() {
        java.lang.Object ref = discription_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          discription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDiscriptionBytes() {
        java.lang.Object ref = discription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          discription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public Builder setDiscription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        discription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public Builder clearDiscription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        discription_ = getDefaultInstance().getDiscription();
        onChanged();
        return this;
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public Builder setDiscriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        discription_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qianxun.model.RoseExchange)
    }

    static {
      defaultInstance = new RoseExchange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qianxun.model.RoseExchange)
    public static final int ROSEEXCHANGE_FIELD_NUMBER = 100;
    /**
     * <code>extend .com.qianxun.model.BaseExchange { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.qianxun.model.BaseExchangeProtos.BaseExchange,
        com.qianxun.model.BaseExchangeProtos.RoseExchange> roseExchange = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.qianxun.model.BaseExchangeProtos.RoseExchange.getDefaultInstance(),
          0,
          com.qianxun.model.BaseExchangeProtos.RoseExchange.class,
          com.qianxun.model.BaseExchangeProtos.RoseExchange.getDefaultInstance());
  }

  public interface GemExchangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 uid = 1;
    /**
     * <code>required int64 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     */
    long getUid();

    // optional int32 count = 2;
    /**
     * <code>optional int32 count = 2;</code>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 2;</code>
     */
    int getCount();

    // required string trend = 3;
    /**
     * <code>required string trend = 3;</code>
     */
    boolean hasTrend();
    /**
     * <code>required string trend = 3;</code>
     */
    java.lang.String getTrend();
    /**
     * <code>required string trend = 3;</code>
     */
    com.google.protobuf.ByteString
        getTrendBytes();

    // required string discription = 4;
    /**
     * <code>required string discription = 4;</code>
     */
    boolean hasDiscription();
    /**
     * <code>required string discription = 4;</code>
     */
    java.lang.String getDiscription();
    /**
     * <code>required string discription = 4;</code>
     */
    com.google.protobuf.ByteString
        getDiscriptionBytes();
  }
  /**
   * Protobuf type {@code com.qianxun.model.GemExchange}
   */
  public static final class GemExchange extends
      com.google.protobuf.GeneratedMessage
      implements GemExchangeOrBuilder {
    // Use GemExchange.newBuilder() to construct.
    private GemExchange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GemExchange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GemExchange defaultInstance;
    public static GemExchange getDefaultInstance() {
      return defaultInstance;
    }

    public GemExchange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GemExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              trend_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              discription_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_GemExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_GemExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianxun.model.BaseExchangeProtos.GemExchange.class, com.qianxun.model.BaseExchangeProtos.GemExchange.Builder.class);
    }

    public static com.google.protobuf.Parser<GemExchange> PARSER =
        new com.google.protobuf.AbstractParser<GemExchange>() {
      public GemExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GemExchange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GemExchange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    // optional int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    // required string trend = 3;
    public static final int TREND_FIELD_NUMBER = 3;
    private java.lang.Object trend_;
    /**
     * <code>required string trend = 3;</code>
     */
    public boolean hasTrend() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string trend = 3;</code>
     */
    public java.lang.String getTrend() {
      java.lang.Object ref = trend_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trend_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string trend = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTrendBytes() {
      java.lang.Object ref = trend_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string discription = 4;
    public static final int DISCRIPTION_FIELD_NUMBER = 4;
    private java.lang.Object discription_;
    /**
     * <code>required string discription = 4;</code>
     */
    public boolean hasDiscription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string discription = 4;</code>
     */
    public java.lang.String getDiscription() {
      java.lang.Object ref = discription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          discription_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string discription = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDiscriptionBytes() {
      java.lang.Object ref = discription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uid_ = 0L;
      count_ = 0;
      trend_ = "";
      discription_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrend()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDiscription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTrendBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDiscriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTrendBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDiscriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qianxun.model.BaseExchangeProtos.GemExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qianxun.model.BaseExchangeProtos.GemExchange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qianxun.model.GemExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qianxun.model.BaseExchangeProtos.GemExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_GemExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_GemExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianxun.model.BaseExchangeProtos.GemExchange.class, com.qianxun.model.BaseExchangeProtos.GemExchange.Builder.class);
      }

      // Construct using com.qianxun.model.BaseExchangeProtos.GemExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        trend_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        discription_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianxun.model.BaseExchangeProtos.internal_static_com_qianxun_model_GemExchange_descriptor;
      }

      public com.qianxun.model.BaseExchangeProtos.GemExchange getDefaultInstanceForType() {
        return com.qianxun.model.BaseExchangeProtos.GemExchange.getDefaultInstance();
      }

      public com.qianxun.model.BaseExchangeProtos.GemExchange build() {
        com.qianxun.model.BaseExchangeProtos.GemExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qianxun.model.BaseExchangeProtos.GemExchange buildPartial() {
        com.qianxun.model.BaseExchangeProtos.GemExchange result = new com.qianxun.model.BaseExchangeProtos.GemExchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.trend_ = trend_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.discription_ = discription_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianxun.model.BaseExchangeProtos.GemExchange) {
          return mergeFrom((com.qianxun.model.BaseExchangeProtos.GemExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianxun.model.BaseExchangeProtos.GemExchange other) {
        if (other == com.qianxun.model.BaseExchangeProtos.GemExchange.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasTrend()) {
          bitField0_ |= 0x00000004;
          trend_ = other.trend_;
          onChanged();
        }
        if (other.hasDiscription()) {
          bitField0_ |= 0x00000008;
          discription_ = other.discription_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasTrend()) {
          
          return false;
        }
        if (!hasDiscription()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianxun.model.BaseExchangeProtos.GemExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianxun.model.BaseExchangeProtos.GemExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 uid = 1;
      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 count = 2;
      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      // required string trend = 3;
      private java.lang.Object trend_ = "";
      /**
       * <code>required string trend = 3;</code>
       */
      public boolean hasTrend() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public java.lang.String getTrend() {
        java.lang.Object ref = trend_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          trend_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTrendBytes() {
        java.lang.Object ref = trend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public Builder setTrend(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        trend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public Builder clearTrend() {
        bitField0_ = (bitField0_ & ~0x00000004);
        trend_ = getDefaultInstance().getTrend();
        onChanged();
        return this;
      }
      /**
       * <code>required string trend = 3;</code>
       */
      public Builder setTrendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        trend_ = value;
        onChanged();
        return this;
      }

      // required string discription = 4;
      private java.lang.Object discription_ = "";
      /**
       * <code>required string discription = 4;</code>
       */
      public boolean hasDiscription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public java.lang.String getDiscription() {
        java.lang.Object ref = discription_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          discription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDiscriptionBytes() {
        java.lang.Object ref = discription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          discription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public Builder setDiscription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        discription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public Builder clearDiscription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        discription_ = getDefaultInstance().getDiscription();
        onChanged();
        return this;
      }
      /**
       * <code>required string discription = 4;</code>
       */
      public Builder setDiscriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        discription_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qianxun.model.GemExchange)
    }

    static {
      defaultInstance = new GemExchange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qianxun.model.GemExchange)
    public static final int GEMEXCHANGE_FIELD_NUMBER = 101;
    /**
     * <code>extend .com.qianxun.model.BaseExchange { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.qianxun.model.BaseExchangeProtos.BaseExchange,
        com.qianxun.model.BaseExchangeProtos.GemExchange> gemExchange = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.qianxun.model.BaseExchangeProtos.GemExchange.getDefaultInstance(),
          0,
          com.qianxun.model.BaseExchangeProtos.GemExchange.class,
          com.qianxun.model.BaseExchangeProtos.GemExchange.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qianxun_model_BaseExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qianxun_model_BaseExchange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qianxun_model_RoseExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qianxun_model_RoseExchange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qianxun_model_GemExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qianxun_model_GemExchange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016exchange.proto\022\021com.qianxun.model\"&\n\014B" +
      "aseExchange\022\014\n\004type\030\001 \002(\t*\010\010d\020\200\200\200\200\002\"\246\001\n\014" +
      "RoseExchange\022\013\n\003uid\030\001 \002(\003\022\r\n\005count\030\002 \001(\005" +
      "\022\r\n\005trend\030\003 \002(\t\022\023\n\013discription\030\004 \002(\t2V\n\014" +
      "roseExchange\022\037.com.qianxun.model.BaseExc" +
      "hange\030d \002(\0132\037.com.qianxun.model.RoseExch" +
      "ange\"\243\001\n\013GemExchange\022\013\n\003uid\030\001 \002(\003\022\r\n\005cou" +
      "nt\030\002 \001(\005\022\r\n\005trend\030\003 \002(\t\022\023\n\013discription\030\004" +
      " \002(\t2T\n\013gemExchange\022\037.com.qianxun.model." +
      "BaseExchange\030e \002(\0132\036.com.qianxun.model.G",
      "emExchangeB\'\n\021com.qianxun.modelB\022BaseExc" +
      "hangeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_qianxun_model_BaseExchange_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_qianxun_model_BaseExchange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_qianxun_model_BaseExchange_descriptor,
              new java.lang.String[] { "Type", });
          internal_static_com_qianxun_model_RoseExchange_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_qianxun_model_RoseExchange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_qianxun_model_RoseExchange_descriptor,
              new java.lang.String[] { "Uid", "Count", "Trend", "Discription", });
          internal_static_com_qianxun_model_GemExchange_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_qianxun_model_GemExchange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_qianxun_model_GemExchange_descriptor,
              new java.lang.String[] { "Uid", "Count", "Trend", "Discription", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
