#server:
#  port: 9000
#application: @name@
spring.datasource:
  url: jdbc:mysql://192.168.0.247:32495?autoReconnect=true&useSSL=false
  username: root
  password: dataSharing
  driver-class-name: com.mysql.cj.jdbc.Driver
