#server:
#  port: 9000
#application: @name@
spring.datasource:
  url: jdbc:mysql://mysql-svc.default:3306?autoReconnect=true&useSSL=false
  username: root
  password: dataSharing
  driver-class-name: com.mysql.cj.jdbc.Driver
