/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package org.teiid.query.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int VARBINARY = 11;
  /** RegularExpression Id. */
  int VARCHAR = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int BYTE = 14;
  /** RegularExpression Id. */
  int TINYINT = 15;
  /** RegularExpression Id. */
  int SHORT = 16;
  /** RegularExpression Id. */
  int SMALLINT = 17;
  /** RegularExpression Id. */
  int CHAR = 18;
  /** RegularExpression Id. */
  int INTEGER = 19;
  /** RegularExpression Id. */
  int LONG = 20;
  /** RegularExpression Id. */
  int BIGINT = 21;
  /** RegularExpression Id. */
  int BIGINTEGER = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int REAL = 24;
  /** RegularExpression Id. */
  int DOUBLE = 25;
  /** RegularExpression Id. */
  int BIGDECIMAL = 26;
  /** RegularExpression Id. */
  int DECIMAL = 27;
  /** RegularExpression Id. */
  int DATE = 28;
  /** RegularExpression Id. */
  int TIME = 29;
  /** RegularExpression Id. */
  int TIMESTAMP = 30;
  /** RegularExpression Id. */
  int BLOB = 31;
  /** RegularExpression Id. */
  int CLOB = 32;
  /** RegularExpression Id. */
  int XML = 33;
  /** RegularExpression Id. */
  int CAST = 34;
  /** RegularExpression Id. */
  int CONVERT = 35;
  /** RegularExpression Id. */
  int ADD = 36;
  /** RegularExpression Id. */
  int ALL = 37;
  /** RegularExpression Id. */
  int ALTER = 38;
  /** RegularExpression Id. */
  int AND = 39;
  /** RegularExpression Id. */
  int ANY = 40;
  /** RegularExpression Id. */
  int ARRAY = 41;
  /** RegularExpression Id. */
  int ARRAY_AGG = 42;
  /** RegularExpression Id. */
  int AS = 43;
  /** RegularExpression Id. */
  int ASC = 44;
  /** RegularExpression Id. */
  int ATOMIC = 45;
  /** RegularExpression Id. */
  int AUTORIZATION = 46;
  /** RegularExpression Id. */
  int BEGIN = 47;
  /** RegularExpression Id. */
  int BETWEEN = 48;
  /** RegularExpression Id. */
  int BINARY = 49;
  /** RegularExpression Id. */
  int BOTH = 50;
  /** RegularExpression Id. */
  int BREAK = 51;
  /** RegularExpression Id. */
  int BY = 52;
  /** RegularExpression Id. */
  int CALL = 53;
  /** RegularExpression Id. */
  int CALLED = 54;
  /** RegularExpression Id. */
  int CASCADED = 55;
  /** RegularExpression Id. */
  int CASE = 56;
  /** RegularExpression Id. */
  int CHARACTER = 57;
  /** RegularExpression Id. */
  int CHECK = 58;
  /** RegularExpression Id. */
  int CLOSE = 59;
  /** RegularExpression Id. */
  int COLLATE = 60;
  /** RegularExpression Id. */
  int COLUMN = 61;
  /** RegularExpression Id. */
  int COMMIT = 62;
  /** RegularExpression Id. */
  int CONNECT = 63;
  /** RegularExpression Id. */
  int CONSTRAINT = 64;
  /** RegularExpression Id. */
  int CONTINUE = 65;
  /** RegularExpression Id. */
  int CORRESPONDING = 66;
  /** RegularExpression Id. */
  int CURRENT_DATE = 67;
  /** RegularExpression Id. */
  int CURRENT_TIME = 68;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 69;
  /** RegularExpression Id. */
  int CURRENT_USER = 70;
  /** RegularExpression Id. */
  int CREATE = 71;
  /** RegularExpression Id. */
  int CRITERIA = 72;
  /** RegularExpression Id. */
  int CROSS = 73;
  /** RegularExpression Id. */
  int CURSOR = 74;
  /** RegularExpression Id. */
  int DAY = 75;
  /** RegularExpression Id. */
  int DEALLOCATE = 76;
  /** RegularExpression Id. */
  int DECLARE = 77;
  /** RegularExpression Id. */
  int DELETE = 78;
  /** RegularExpression Id. */
  int DESC = 79;
  /** RegularExpression Id. */
  int DESCRIBE = 80;
  /** RegularExpression Id. */
  int DETERMINISTIC = 81;
  /** RegularExpression Id. */
  int DISCONNECT = 82;
  /** RegularExpression Id. */
  int DISTINCT = 83;
  /** RegularExpression Id. */
  int DROP = 84;
  /** RegularExpression Id. */
  int EACH = 85;
  /** RegularExpression Id. */
  int ELSE = 86;
  /** RegularExpression Id. */
  int END = 87;
  /** RegularExpression Id. */
  int ERROR = 88;
  /** RegularExpression Id. */
  int ESCAPE = 89;
  /** RegularExpression Id. */
  int EXCEPT = 90;
  /** RegularExpression Id. */
  int EXEC = 91;
  /** RegularExpression Id. */
  int EXECUTE = 92;
  /** RegularExpression Id. */
  int EXTERNAL = 93;
  /** RegularExpression Id. */
  int EXISTS = 94;
  /** RegularExpression Id. */
  int FALSE = 95;
  /** RegularExpression Id. */
  int FETCH = 96;
  /** RegularExpression Id. */
  int FILTER = 97;
  /** RegularExpression Id. */
  int FOR = 98;
  /** RegularExpression Id. */
  int FOREIGN = 99;
  /** RegularExpression Id. */
  int FROM = 100;
  /** RegularExpression Id. */
  int FULL = 101;
  /** RegularExpression Id. */
  int FUNCTION = 102;
  /** RegularExpression Id. */
  int GET = 103;
  /** RegularExpression Id. */
  int GLOBAL = 104;
  /** RegularExpression Id. */
  int GRANT = 105;
  /** RegularExpression Id. */
  int GROUP = 106;
  /** RegularExpression Id. */
  int HAS = 107;
  /** RegularExpression Id. */
  int HAVING = 108;
  /** RegularExpression Id. */
  int HOLD = 109;
  /** RegularExpression Id. */
  int HOUR = 110;
  /** RegularExpression Id. */
  int IF = 111;
  /** RegularExpression Id. */
  int IDENTITY = 112;
  /** RegularExpression Id. */
  int IMMEDIATE = 113;
  /** RegularExpression Id. */
  int IN = 114;
  /** RegularExpression Id. */
  int INDICATOR = 115;
  /** RegularExpression Id. */
  int INNER = 116;
  /** RegularExpression Id. */
  int INPUT = 117;
  /** RegularExpression Id. */
  int INOUT = 118;
  /** RegularExpression Id. */
  int INSENSITIVE = 119;
  /** RegularExpression Id. */
  int INSERT = 120;
  /** RegularExpression Id. */
  int INTERSECT = 121;
  /** RegularExpression Id. */
  int INTERVAL = 122;
  /** RegularExpression Id. */
  int INTO = 123;
  /** RegularExpression Id. */
  int IS = 124;
  /** RegularExpression Id. */
  int ISOLATION = 125;
  /** RegularExpression Id. */
  int JOIN = 126;
  /** RegularExpression Id. */
  int LEFT = 127;
  /** RegularExpression Id. */
  int LANGUAGE = 128;
  /** RegularExpression Id. */
  int LARGE = 129;
  /** RegularExpression Id. */
  int LEADING = 130;
  /** RegularExpression Id. */
  int LEAVE = 131;
  /** RegularExpression Id. */
  int LIKE = 132;
  /** RegularExpression Id. */
  int LIKE_REGEX = 133;
  /** RegularExpression Id. */
  int LIMIT = 134;
  /** RegularExpression Id. */
  int LOCAL = 135;
  /** RegularExpression Id. */
  int LOOP = 136;
  /** RegularExpression Id. */
  int MAKEDEP = 137;
  /** RegularExpression Id. */
  int MAKEIND = 138;
  /** RegularExpression Id. */
  int MAKENOTDEP = 139;
  /** RegularExpression Id. */
  int MATCH = 140;
  /** RegularExpression Id. */
  int MERGE = 141;
  /** RegularExpression Id. */
  int METHOD = 142;
  /** RegularExpression Id. */
  int MINUTE = 143;
  /** RegularExpression Id. */
  int MODIFIES = 144;
  /** RegularExpression Id. */
  int MODULE = 145;
  /** RegularExpression Id. */
  int MONTH = 146;
  /** RegularExpression Id. */
  int NATURAL = 147;
  /** RegularExpression Id. */
  int NEW = 148;
  /** RegularExpression Id. */
  int NOCACHE = 149;
  /** RegularExpression Id. */
  int NO = 150;
  /** RegularExpression Id. */
  int NOT = 151;
  /** RegularExpression Id. */
  int NULL = 152;
  /** RegularExpression Id. */
  int OF = 153;
  /** RegularExpression Id. */
  int OFFSET = 154;
  /** RegularExpression Id. */
  int OLD = 155;
  /** RegularExpression Id. */
  int ON = 156;
  /** RegularExpression Id. */
  int ONLY = 157;
  /** RegularExpression Id. */
  int OPEN = 158;
  /** RegularExpression Id. */
  int OPTION = 159;
  /** RegularExpression Id. */
  int OPTIONS = 160;
  /** RegularExpression Id. */
  int OR = 161;
  /** RegularExpression Id. */
  int ORDER = 162;
  /** RegularExpression Id. */
  int OUT = 163;
  /** RegularExpression Id. */
  int OUTER = 164;
  /** RegularExpression Id. */
  int OUTPUT = 165;
  /** RegularExpression Id. */
  int OVER = 166;
  /** RegularExpression Id. */
  int OVERLAPS = 167;
  /** RegularExpression Id. */
  int PARAMETER = 168;
  /** RegularExpression Id. */
  int PARTITION = 169;
  /** RegularExpression Id. */
  int PRECISION = 170;
  /** RegularExpression Id. */
  int PREPARE = 171;
  /** RegularExpression Id. */
  int PRIMARY = 172;
  /** RegularExpression Id. */
  int PROCEDURE = 173;
  /** RegularExpression Id. */
  int RANGE = 174;
  /** RegularExpression Id. */
  int READS = 175;
  /** RegularExpression Id. */
  int RECURSIVE = 176;
  /** RegularExpression Id. */
  int REFERENCES = 177;
  /** RegularExpression Id. */
  int REFERENCING = 178;
  /** RegularExpression Id. */
  int RETURN = 179;
  /** RegularExpression Id. */
  int RETURNS = 180;
  /** RegularExpression Id. */
  int REVOKE = 181;
  /** RegularExpression Id. */
  int RIGHT = 182;
  /** RegularExpression Id. */
  int ROLLBACK = 183;
  /** RegularExpression Id. */
  int ROLLUP = 184;
  /** RegularExpression Id. */
  int ROW = 185;
  /** RegularExpression Id. */
  int ROWS = 186;
  /** RegularExpression Id. */
  int SAVEPOINT = 187;
  /** RegularExpression Id. */
  int SCROLL = 188;
  /** RegularExpression Id. */
  int SEARCH = 189;
  /** RegularExpression Id. */
  int SECOND = 190;
  /** RegularExpression Id. */
  int SELECT = 191;
  /** RegularExpression Id. */
  int SENSITIVE = 192;
  /** RegularExpression Id. */
  int SESSION_USER = 193;
  /** RegularExpression Id. */
  int SET = 194;
  /** RegularExpression Id. */
  int SIMILAR = 195;
  /** RegularExpression Id. */
  int SPECIFIC = 196;
  /** RegularExpression Id. */
  int SOME = 197;
  /** RegularExpression Id. */
  int SQL = 198;
  /** RegularExpression Id. */
  int SQLEXCEPTION = 199;
  /** RegularExpression Id. */
  int SQLSTATE = 200;
  /** RegularExpression Id. */
  int SQLWARNING = 201;
  /** RegularExpression Id. */
  int START = 202;
  /** RegularExpression Id. */
  int STATIC = 203;
  /** RegularExpression Id. */
  int SYSTEM = 204;
  /** RegularExpression Id. */
  int SYSTEM_USER = 205;
  /** RegularExpression Id. */
  int TABLE = 206;
  /** RegularExpression Id. */
  int TEMPORARY = 207;
  /** RegularExpression Id. */
  int THEN = 208;
  /** RegularExpression Id. */
  int TIMEZONE_HOUR = 209;
  /** RegularExpression Id. */
  int TIMEZONE_MINUTE = 210;
  /** RegularExpression Id. */
  int TO = 211;
  /** RegularExpression Id. */
  int TRAILING = 212;
  /** RegularExpression Id. */
  int TRANSLATE = 213;
  /** RegularExpression Id. */
  int TRIGGER = 214;
  /** RegularExpression Id. */
  int TRUE = 215;
  /** RegularExpression Id. */
  int UNION = 216;
  /** RegularExpression Id. */
  int UNIQUE = 217;
  /** RegularExpression Id. */
  int UNKNOWN = 218;
  /** RegularExpression Id. */
  int USER = 219;
  /** RegularExpression Id. */
  int UPDATE = 220;
  /** RegularExpression Id. */
  int USING = 221;
  /** RegularExpression Id. */
  int VALUE = 222;
  /** RegularExpression Id. */
  int VALUES = 223;
  /** RegularExpression Id. */
  int VIRTUAL = 224;
  /** RegularExpression Id. */
  int WHEN = 225;
  /** RegularExpression Id. */
  int WHENEVER = 226;
  /** RegularExpression Id. */
  int WHERE = 227;
  /** RegularExpression Id. */
  int WITH = 228;
  /** RegularExpression Id. */
  int WHILE = 229;
  /** RegularExpression Id. */
  int WINDOW = 230;
  /** RegularExpression Id. */
  int WITHIN = 231;
  /** RegularExpression Id. */
  int WITHOUT = 232;
  /** RegularExpression Id. */
  int YEAR = 233;
  /** RegularExpression Id. */
  int ALLOCATE = 234;
  /** RegularExpression Id. */
  int ARE = 235;
  /** RegularExpression Id. */
  int ASENSITIVE = 236;
  /** RegularExpression Id. */
  int ASYMETRIC = 237;
  /** RegularExpression Id. */
  int CYCLE = 238;
  /** RegularExpression Id. */
  int DEC = 239;
  /** RegularExpression Id. */
  int DEREF = 240;
  /** RegularExpression Id. */
  int DYNAMIC = 241;
  /** RegularExpression Id. */
  int ELEMENT = 242;
  /** RegularExpression Id. */
  int FREE = 243;
  /** RegularExpression Id. */
  int INT = 244;
  /** RegularExpression Id. */
  int LATERAL = 245;
  /** RegularExpression Id. */
  int LOCALTIME = 246;
  /** RegularExpression Id. */
  int LOCALTIMESTAMP = 247;
  /** RegularExpression Id. */
  int MEMBER = 248;
  /** RegularExpression Id. */
  int MULTISET = 249;
  /** RegularExpression Id. */
  int NATIONAL = 250;
  /** RegularExpression Id. */
  int NCHAR = 251;
  /** RegularExpression Id. */
  int NCLOB = 252;
  /** RegularExpression Id. */
  int NUMERIC = 253;
  /** RegularExpression Id. */
  int RELEASE = 254;
  /** RegularExpression Id. */
  int SPECIFICTYPE = 255;
  /** RegularExpression Id. */
  int SYMETRIC = 256;
  /** RegularExpression Id. */
  int SUBMULTILIST = 257;
  /** RegularExpression Id. */
  int TRANSLATION = 258;
  /** RegularExpression Id. */
  int TREAT = 259;
  /** RegularExpression Id. */
  int VARYING = 260;
  /** RegularExpression Id. */
  int XMLAGG = 261;
  /** RegularExpression Id. */
  int XMLATTRIBUTES = 262;
  /** RegularExpression Id. */
  int XMLBINARY = 263;
  /** RegularExpression Id. */
  int XMLCAST = 264;
  /** RegularExpression Id. */
  int XMLCONCAT = 265;
  /** RegularExpression Id. */
  int XMLCOMMENT = 266;
  /** RegularExpression Id. */
  int XMLDOCUMENT = 267;
  /** RegularExpression Id. */
  int XMLELEMENT = 268;
  /** RegularExpression Id. */
  int XMLEXISTS = 269;
  /** RegularExpression Id. */
  int XMLFOREST = 270;
  /** RegularExpression Id. */
  int XMLITERATE = 271;
  /** RegularExpression Id. */
  int XMLNAMESPACES = 272;
  /** RegularExpression Id. */
  int XMLPARSE = 273;
  /** RegularExpression Id. */
  int XMLPI = 274;
  /** RegularExpression Id. */
  int XMLQUERY = 275;
  /** RegularExpression Id. */
  int XMLSERIALIZE = 276;
  /** RegularExpression Id. */
  int XMLTABLE = 277;
  /** RegularExpression Id. */
  int XMLTEXT = 278;
  /** RegularExpression Id. */
  int XMLVALIDATE = 279;
  /** RegularExpression Id. */
  int DATALINK = 280;
  /** RegularExpression Id. */
  int DLNEWCOPY = 281;
  /** RegularExpression Id. */
  int DLPREVIOUSCOPY = 282;
  /** RegularExpression Id. */
  int DLURLCOMPLETE = 283;
  /** RegularExpression Id. */
  int DLURLCOMPLETEWRITE = 284;
  /** RegularExpression Id. */
  int DLURLCOMPLETEONLY = 285;
  /** RegularExpression Id. */
  int DLURLPATH = 286;
  /** RegularExpression Id. */
  int DLURLPATHWRITE = 287;
  /** RegularExpression Id. */
  int DLURLPATHONLY = 288;
  /** RegularExpression Id. */
  int DLURLSCHEME = 289;
  /** RegularExpression Id. */
  int DLURLSERVER = 290;
  /** RegularExpression Id. */
  int DLVALUE = 291;
  /** RegularExpression Id. */
  int IMPORT = 292;
  /** RegularExpression Id. */
  int INSTEAD = 293;
  /** RegularExpression Id. */
  int ENABLED = 294;
  /** RegularExpression Id. */
  int DISABLED = 295;
  /** RegularExpression Id. */
  int VIEW = 296;
  /** RegularExpression Id. */
  int KEY = 297;
  /** RegularExpression Id. */
  int SERIAL = 298;
  /** RegularExpression Id. */
  int TEXTAGG = 299;
  /** RegularExpression Id. */
  int COUNT_BIG = 300;
  /** RegularExpression Id. */
  int COUNT = 301;
  /** RegularExpression Id. */
  int ROW_NUMBER = 302;
  /** RegularExpression Id. */
  int RANK = 303;
  /** RegularExpression Id. */
  int DENSE_RANK = 304;
  /** RegularExpression Id. */
  int PERCENT_RANK = 305;
  /** RegularExpression Id. */
  int CUME_DIST = 306;
  /** RegularExpression Id. */
  int CURRENT = 307;
  /** RegularExpression Id. */
  int UNBOUNDED = 308;
  /** RegularExpression Id. */
  int PRECEDING = 309;
  /** RegularExpression Id. */
  int FOLLOWING = 310;
  /** RegularExpression Id. */
  int SUM = 311;
  /** RegularExpression Id. */
  int AVG = 312;
  /** RegularExpression Id. */
  int MIN = 313;
  /** RegularExpression Id. */
  int MAX = 314;
  /** RegularExpression Id. */
  int EVERY = 315;
  /** RegularExpression Id. */
  int STDDEV_POP = 316;
  /** RegularExpression Id. */
  int STDDEV_SAMP = 317;
  /** RegularExpression Id. */
  int VAR_SAMP = 318;
  /** RegularExpression Id. */
  int VAR_POP = 319;
  /** RegularExpression Id. */
  int DOCUMENT = 320;
  /** RegularExpression Id. */
  int CONTENT = 321;
  /** RegularExpression Id. */
  int TRIM = 322;
  /** RegularExpression Id. */
  int EMPTY = 323;
  /** RegularExpression Id. */
  int ORDINALITY = 324;
  /** RegularExpression Id. */
  int PATH = 325;
  /** RegularExpression Id. */
  int FIRST = 326;
  /** RegularExpression Id. */
  int LAST = 327;
  /** RegularExpression Id. */
  int NEXT = 328;
  /** RegularExpression Id. */
  int SUBSTRING = 329;
  /** RegularExpression Id. */
  int EXTRACT = 330;
  /** RegularExpression Id. */
  int TO_CHARS = 331;
  /** RegularExpression Id. */
  int TO_BYTES = 332;
  /** RegularExpression Id. */
  int TIMESTAMPADD = 333;
  /** RegularExpression Id. */
  int TIMESTAMPDIFF = 334;
  /** RegularExpression Id. */
  int QUERYSTRING = 335;
  /** RegularExpression Id. */
  int NAMESPACE = 336;
  /** RegularExpression Id. */
  int RESULT = 337;
  /** RegularExpression Id. */
  int INDEX = 338;
  /** RegularExpression Id. */
  int ACCESSPATTERN = 339;
  /** RegularExpression Id. */
  int AUTO_INCREMENT = 340;
  /** RegularExpression Id. */
  int WELLFORMED = 341;
  /** RegularExpression Id. */
  int SQL_TSI_FRAC_SECOND = 342;
  /** RegularExpression Id. */
  int SQL_TSI_SECOND = 343;
  /** RegularExpression Id. */
  int SQL_TSI_MINUTE = 344;
  /** RegularExpression Id. */
  int SQL_TSI_HOUR = 345;
  /** RegularExpression Id. */
  int SQL_TSI_DAY = 346;
  /** RegularExpression Id. */
  int SQL_TSI_WEEK = 347;
  /** RegularExpression Id. */
  int SQL_TSI_MONTH = 348;
  /** RegularExpression Id. */
  int SQL_TSI_QUARTER = 349;
  /** RegularExpression Id. */
  int SQL_TSI_YEAR = 350;
  /** RegularExpression Id. */
  int TEXTTABLE = 351;
  /** RegularExpression Id. */
  int ARRAYTABLE = 352;
  /** RegularExpression Id. */
  int JSONTABLE = 353;
  /** RegularExpression Id. */
  int SELECTOR = 354;
  /** RegularExpression Id. */
  int SKIP_KEYWORD = 355;
  /** RegularExpression Id. */
  int WIDTH = 356;
  /** RegularExpression Id. */
  int PASSING = 357;
  /** RegularExpression Id. */
  int NAME = 358;
  /** RegularExpression Id. */
  int ENCODING = 359;
  /** RegularExpression Id. */
  int COLUMNS = 360;
  /** RegularExpression Id. */
  int DELIMITER = 361;
  /** RegularExpression Id. */
  int QUOTE = 362;
  /** RegularExpression Id. */
  int HEADER = 363;
  /** RegularExpression Id. */
  int NULLS = 364;
  /** RegularExpression Id. */
  int OBJECTTABLE = 365;
  /** RegularExpression Id. */
  int VERSION = 366;
  /** RegularExpression Id. */
  int INCLUDING = 367;
  /** RegularExpression Id. */
  int EXCLUDING = 368;
  /** RegularExpression Id. */
  int XMLDECLARATION = 369;
  /** RegularExpression Id. */
  int VARIADIC = 370;
  /** RegularExpression Id. */
  int EXCEPTION = 371;
  /** RegularExpression Id. */
  int RAISE = 372;
  /** RegularExpression Id. */
  int CHAIN = 373;
  /** RegularExpression Id. */
  int JSON = 374;
  /** RegularExpression Id. */
  int JSONARRAY_AGG = 375;
  /** RegularExpression Id. */
  int JSONOBJECT = 376;
  /** RegularExpression Id. */
  int PRESERVE = 377;
  /** RegularExpression Id. */
  int GEOMETRY = 378;
  /** RegularExpression Id. */
  int GEOGRAPHY = 379;
  /** RegularExpression Id. */
  int UPSERT = 380;
  /** RegularExpression Id. */
  int AFTER = 381;
  /** RegularExpression Id. */
  int DEFAULT_KEYWORD = 382;
  /** RegularExpression Id. */
  int AUTHENTICATED = 383;
  /** RegularExpression Id. */
  int TYPE = 384;
  /** RegularExpression Id. */
  int TRANSLATOR = 385;
  /** RegularExpression Id. */
  int JAAS = 386;
  /** RegularExpression Id. */
  int CONDITION = 387;
  /** RegularExpression Id. */
  int MASK = 388;
  /** RegularExpression Id. */
  int ACCESS = 389;
  /** RegularExpression Id. */
  int CONTROL = 390;
  /** RegularExpression Id. */
  int NONE = 391;
  /** RegularExpression Id. */
  int DATA = 392;
  /** RegularExpression Id. */
  int DATABASE = 393;
  /** RegularExpression Id. */
  int PRIVILEGES = 394;
  /** RegularExpression Id. */
  int SCHEMA = 395;
  /** RegularExpression Id. */
  int ROLE = 396;
  /** RegularExpression Id. */
  int USE = 397;
  /** RegularExpression Id. */
  int SERVER = 398;
  /** RegularExpression Id. */
  int WRAPPER = 399;
  /** RegularExpression Id. */
  int REPOSITORY = 400;
  /** RegularExpression Id. */
  int RENAME = 401;
  /** RegularExpression Id. */
  int DOMAIN = 402;
  /** RegularExpression Id. */
  int USAGE = 403;
  /** RegularExpression Id. */
  int POSITION = 404;
  /** RegularExpression Id. */
  int LISTAGG = 405;
  /** RegularExpression Id. */
  int OBJECT = 406;
  /** RegularExpression Id. */
  int EXPLAIN = 407;
  /** RegularExpression Id. */
  int ANALYZE = 408;
  /** RegularExpression Id. */
  int TEXT = 409;
  /** RegularExpression Id. */
  int FORMAT = 410;
  /** RegularExpression Id. */
  int YAML = 411;
  /** RegularExpression Id. */
  int HANDLER = 412;
  /** RegularExpression Id. */
  int POLICY = 413;
  /** RegularExpression Id. */
  int EPOCH = 414;
  /** RegularExpression Id. */
  int QUARTER = 415;
  /** RegularExpression Id. */
  int DOW = 416;
  /** RegularExpression Id. */
  int DOY = 417;
  /** RegularExpression Id. */
  int ALL_IN_GROUP = 418;
  /** RegularExpression Id. */
  int ID = 419;
  /** RegularExpression Id. */
  int QUOTED_ID = 420;
  /** RegularExpression Id. */
  int ID_PART = 421;
  /** RegularExpression Id. */
  int ESCAPEDFUNCTION = 422;
  /** RegularExpression Id. */
  int ESCAPEDJOIN = 423;
  /** RegularExpression Id. */
  int ESCAPEDTYPE = 424;
  /** RegularExpression Id. */
  int DECIMALVAL = 425;
  /** RegularExpression Id. */
  int FLOATVAL = 426;
  /** RegularExpression Id. */
  int STRINGVAL = 427;
  /** RegularExpression Id. */
  int LETTER = 428;
  /** RegularExpression Id. */
  int DIGIT = 429;
  /** RegularExpression Id. */
  int UNSIGNEDINTEGER = 430;
  /** RegularExpression Id. */
  int BINARYSTRINGVAL = 431;
  /** RegularExpression Id. */
  int HEXIT = 432;
  /** RegularExpression Id. */
  int COMMA = 433;
  /** RegularExpression Id. */
  int PERIOD = 434;
  /** RegularExpression Id. */
  int LPAREN = 435;
  /** RegularExpression Id. */
  int RPAREN = 436;
  /** RegularExpression Id. */
  int LBRACE = 437;
  /** RegularExpression Id. */
  int RBRACE = 438;
  /** RegularExpression Id. */
  int LSBRACE = 439;
  /** RegularExpression Id. */
  int RSBRACE = 440;
  /** RegularExpression Id. */
  int EQ = 441;
  /** RegularExpression Id. */
  int NE = 442;
  /** RegularExpression Id. */
  int NE2 = 443;
  /** RegularExpression Id. */
  int LT = 444;
  /** RegularExpression Id. */
  int LE = 445;
  /** RegularExpression Id. */
  int GT = 446;
  /** RegularExpression Id. */
  int GE = 447;
  /** RegularExpression Id. */
  int STAR = 448;
  /** RegularExpression Id. */
  int SLASH = 449;
  /** RegularExpression Id. */
  int PLUS = 450;
  /** RegularExpression Id. */
  int MINUS = 451;
  /** RegularExpression Id. */
  int QMARK = 452;
  /** RegularExpression Id. */
  int DOLLAR = 453;
  /** RegularExpression Id. */
  int SEMICOLON = 454;
  /** RegularExpression Id. */
  int COLON = 455;
  /** RegularExpression Id. */
  int CONCAT_OP = 456;
  /** RegularExpression Id. */
  int DOUBLE_AMP_OP = 457;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<LINE_COMMENT>",
    "\"string\"",
    "\"varbinary\"",
    "\"varchar\"",
    "\"boolean\"",
    "\"byte\"",
    "\"tinyint\"",
    "\"short\"",
    "\"smallint\"",
    "\"char\"",
    "\"integer\"",
    "\"long\"",
    "\"bigint\"",
    "\"biginteger\"",
    "\"float\"",
    "\"real\"",
    "\"double\"",
    "\"bigdecimal\"",
    "\"decimal\"",
    "\"date\"",
    "\"time\"",
    "\"timestamp\"",
    "\"blob\"",
    "\"clob\"",
    "\"xml\"",
    "\"cast\"",
    "\"convert\"",
    "\"add\"",
    "\"all\"",
    "\"alter\"",
    "\"and\"",
    "\"any\"",
    "\"array\"",
    "\"array_agg\"",
    "\"as\"",
    "\"asc\"",
    "\"atomic\"",
    "\"authorization\"",
    "\"begin\"",
    "\"between\"",
    "\"binary\"",
    "\"both\"",
    "\"break\"",
    "\"by\"",
    "\"call\"",
    "\"called\"",
    "\"cascaded\"",
    "\"case\"",
    "\"character\"",
    "\"check\"",
    "\"close\"",
    "\"collate\"",
    "\"column\"",
    "\"commit\"",
    "\"connect\"",
    "\"constraint\"",
    "\"continue\"",
    "\"corresponding\"",
    "\"current_date\"",
    "\"current_time\"",
    "\"current_timestamp\"",
    "\"current_user\"",
    "\"create\"",
    "\"criteria\"",
    "\"cross\"",
    "\"cursor\"",
    "\"day\"",
    "\"deallocate\"",
    "\"declare\"",
    "\"delete\"",
    "\"desc\"",
    "\"describe\"",
    "\"deterministic\"",
    "\"disconnect\"",
    "\"distinct\"",
    "\"drop\"",
    "\"each\"",
    "\"else\"",
    "\"end\"",
    "\"error\"",
    "\"escape\"",
    "\"except\"",
    "\"exec\"",
    "\"execute\"",
    "\"external\"",
    "\"exists\"",
    "\"false\"",
    "\"fetch\"",
    "\"filter\"",
    "\"for\"",
    "\"foreign\"",
    "\"from\"",
    "\"full\"",
    "\"function\"",
    "\"get\"",
    "\"global\"",
    "\"grant\"",
    "\"group\"",
    "\"has\"",
    "\"having\"",
    "\"hold\"",
    "\"hour\"",
    "\"if\"",
    "\"identity\"",
    "\"immediate\"",
    "\"in\"",
    "\"indicator\"",
    "\"inner\"",
    "\"input\"",
    "\"inout\"",
    "\"insensitive\"",
    "\"insert\"",
    "\"intersect\"",
    "\"interval\"",
    "\"into\"",
    "\"is\"",
    "\"isolation\"",
    "\"join\"",
    "\"left\"",
    "\"language\"",
    "\"large\"",
    "\"leading\"",
    "\"leave\"",
    "\"like\"",
    "\"like_regex\"",
    "\"limit\"",
    "\"local\"",
    "\"loop\"",
    "\"makedep\"",
    "\"makeind\"",
    "\"makenotdep\"",
    "\"match\"",
    "\"merge\"",
    "\"method\"",
    "\"minute\"",
    "\"modifies\"",
    "\"module\"",
    "\"month\"",
    "\"natural\"",
    "\"new\"",
    "\"nocache\"",
    "\"no\"",
    "\"not\"",
    "\"null\"",
    "\"of\"",
    "\"offset\"",
    "\"old\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"options\"",
    "\"or\"",
    "\"order\"",
    "\"out\"",
    "\"outer\"",
    "\"output\"",
    "\"over\"",
    "\"OVERLAPS\"",
    "\"parameter\"",
    "\"partition\"",
    "\"precision\"",
    "\"prepare\"",
    "\"primary\"",
    "\"procedure\"",
    "\"range\"",
    "\"reads\"",
    "\"recursive\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"return\"",
    "\"returns\"",
    "\"REVOKE\"",
    "\"right\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"row\"",
    "\"rows\"",
    "\"savepoint\"",
    "\"scroll\"",
    "\"search\"",
    "\"second\"",
    "\"select\"",
    "\"sensitive\"",
    "\"session_user\"",
    "\"set\"",
    "\"similar\"",
    "\"specific\"",
    "\"some\"",
    "\"sql\"",
    "\"sqlexception\"",
    "\"sqlstate\"",
    "\"sqlwarning\"",
    "\"start\"",
    "\"static\"",
    "\"system\"",
    "\"system_user\"",
    "\"table\"",
    "\"temporary\"",
    "\"then\"",
    "\"timezone_hour\"",
    "\"timezone_minute\"",
    "\"to\"",
    "\"trailing\"",
    "\"translate\"",
    "\"trigger\"",
    "\"true\"",
    "\"union\"",
    "\"unique\"",
    "\"unknown\"",
    "\"user\"",
    "\"update\"",
    "\"using\"",
    "\"value\"",
    "\"values\"",
    "\"virtual\"",
    "\"when\"",
    "\"whenever\"",
    "\"where\"",
    "\"with\"",
    "\"while\"",
    "\"window\"",
    "\"within\"",
    "\"without\"",
    "\"year\"",
    "\"allocate\"",
    "\"are\"",
    "\"asensitive\"",
    "\"asymetric\"",
    "\"cycle\"",
    "\"dec\"",
    "\"deref\"",
    "\"dynamic\"",
    "\"element\"",
    "\"free\"",
    "\"int\"",
    "\"lateral\"",
    "\"localtime\"",
    "\"localtimestamp\"",
    "\"member\"",
    "\"multiset\"",
    "\"national\"",
    "\"nchar\"",
    "\"nclob\"",
    "\"numeric\"",
    "\"release\"",
    "\"specifictype\"",
    "\"symetric\"",
    "\"submultilist\"",
    "\"translation\"",
    "\"treat\"",
    "\"varying\"",
    "\"xmlagg\"",
    "\"xmlattributes\"",
    "\"xmlbinary\"",
    "\"xmlcast\"",
    "\"xmlconcat\"",
    "\"xmlcomment\"",
    "\"xmldocument\"",
    "\"xmlelement\"",
    "\"xmlexists\"",
    "\"xmlforest\"",
    "\"xmliterate\"",
    "\"xmlnamespaces\"",
    "\"xmlparse\"",
    "\"xmlpi\"",
    "\"xmlquery\"",
    "\"xmlserialize\"",
    "\"xmltable\"",
    "\"xmltext\"",
    "\"xmlvalidate\"",
    "\"datalink\"",
    "\"dlnewcopy\"",
    "\"dlpreviouscopy\"",
    "\"dlurlcomplete\"",
    "\"dlurlcompletewrite\"",
    "\"dlurlcompleteonly\"",
    "\"dlurlpath\"",
    "\"dlurlpathwrite\"",
    "\"dlurlpathonly\"",
    "\"dlurlscheme\"",
    "\"dlurlserver\"",
    "\"dlvalue\"",
    "\"import\"",
    "\"instead\"",
    "\"enabled\"",
    "\"disabled\"",
    "\"view\"",
    "\"key\"",
    "\"serial\"",
    "\"textagg\"",
    "\"count_big\"",
    "\"count\"",
    "\"row_number\"",
    "\"rank\"",
    "\"dense_rank\"",
    "\"percent_rank\"",
    "\"cume_dist\"",
    "\"current\"",
    "\"unbounded\"",
    "\"preceding\"",
    "\"following\"",
    "\"sum\"",
    "\"avg\"",
    "\"min\"",
    "\"max\"",
    "\"every\"",
    "\"stddev_pop\"",
    "\"stddev_samp\"",
    "\"var_samp\"",
    "\"var_pop\"",
    "\"document\"",
    "\"content\"",
    "\"trim\"",
    "\"empty\"",
    "\"ordinality\"",
    "\"path\"",
    "\"first\"",
    "\"last\"",
    "\"next\"",
    "\"substring\"",
    "\"extract\"",
    "\"to_chars\"",
    "\"to_bytes\"",
    "\"timestampadd\"",
    "\"timestampdiff\"",
    "\"querystring\"",
    "\"namespace\"",
    "\"result\"",
    "\"index\"",
    "\"accesspattern\"",
    "\"auto_increment\"",
    "\"wellformed\"",
    "\"sql_tsi_frac_second\"",
    "\"sql_tsi_second\"",
    "\"sql_tsi_minute\"",
    "\"sql_tsi_hour\"",
    "\"sql_tsi_day\"",
    "\"sql_tsi_week\"",
    "\"sql_tsi_month\"",
    "\"sql_tsi_quarter\"",
    "\"sql_tsi_year\"",
    "\"texttable\"",
    "\"arraytable\"",
    "\"jsontable\"",
    "\"selector\"",
    "\"skip\"",
    "\"width\"",
    "\"passing\"",
    "\"name\"",
    "\"encoding\"",
    "\"columns\"",
    "\"delimiter\"",
    "\"quote\"",
    "\"header\"",
    "\"nulls\"",
    "\"objecttable\"",
    "\"version\"",
    "\"including\"",
    "\"excluding\"",
    "\"xmldeclaration\"",
    "\"variadic\"",
    "\"exception\"",
    "\"raise\"",
    "\"chain\"",
    "\"json\"",
    "\"jsonarray_agg\"",
    "\"jsonobject\"",
    "\"preserve\"",
    "\"geometry\"",
    "\"geography\"",
    "\"upsert\"",
    "\"after\"",
    "\"default\"",
    "\"authenticated\"",
    "\"type\"",
    "\"translator\"",
    "\"jaas\"",
    "\"condition\"",
    "\"mask\"",
    "\"access\"",
    "\"control\"",
    "\"none\"",
    "\"data\"",
    "\"database\"",
    "\"privileges\"",
    "\"schema\"",
    "\"role\"",
    "\"use\"",
    "\"server\"",
    "\"wrapper\"",
    "\"repository\"",
    "\"rename\"",
    "\"domain\"",
    "\"usage\"",
    "\"position\"",
    "\"listagg\"",
    "\"object\"",
    "\"explain\"",
    "\"analyze\"",
    "\"text\"",
    "\"format\"",
    "\"yaml\"",
    "\"handler\"",
    "\"policy\"",
    "\"epoch\"",
    "\"quarter\"",
    "\"dow\"",
    "\"doy\"",
    "<ALL_IN_GROUP>",
    "<ID>",
    "<QUOTED_ID>",
    "<ID_PART>",
    "<ESCAPEDFUNCTION>",
    "<ESCAPEDJOIN>",
    "<ESCAPEDTYPE>",
    "<DECIMALVAL>",
    "<FLOATVAL>",
    "<STRINGVAL>",
    "<LETTER>",
    "<DIGIT>",
    "<UNSIGNEDINTEGER>",
    "<BINARYSTRINGVAL>",
    "<HEXIT>",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"<>\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"?\"",
    "\"$\"",
    "\";\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
  };

}
