// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc/flight.proto

package com.metasoft.flying.node;

public final class FlightProto {
  private FlightProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PvpSearchRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 uid = 1;
    /**
     * <code>required int64 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     */
    long getUid();

    // required int32 gold = 2;
    /**
     * <code>required int32 gold = 2;</code>
     */
    boolean hasGold();
    /**
     * <code>required int32 gold = 2;</code>
     */
    int getGold();
  }
  /**
   * Protobuf type {@code com.metasoft.node.PvpSearchRequest}
   */
  public static final class PvpSearchRequest extends
      com.google.protobuf.GeneratedMessage
      implements PvpSearchRequestOrBuilder {
    // Use PvpSearchRequest.newBuilder() to construct.
    private PvpSearchRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PvpSearchRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PvpSearchRequest defaultInstance;
    public static PvpSearchRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PvpSearchRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PvpSearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gold_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.metasoft.flying.node.FlightProto.PvpSearchRequest.class, com.metasoft.flying.node.FlightProto.PvpSearchRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PvpSearchRequest> PARSER =
        new com.google.protobuf.AbstractParser<PvpSearchRequest>() {
      public PvpSearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PvpSearchRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PvpSearchRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    // required int32 gold = 2;
    public static final int GOLD_FIELD_NUMBER = 2;
    private int gold_;
    /**
     * <code>required int32 gold = 2;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 gold = 2;</code>
     */
    public int getGold() {
      return gold_;
    }

    private void initFields() {
      uid_ = 0L;
      gold_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, gold_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gold_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.metasoft.flying.node.FlightProto.PvpSearchRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.metasoft.node.PvpSearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.metasoft.flying.node.FlightProto.PvpSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.metasoft.flying.node.FlightProto.PvpSearchRequest.class, com.metasoft.flying.node.FlightProto.PvpSearchRequest.Builder.class);
      }

      // Construct using com.metasoft.flying.node.FlightProto.PvpSearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchRequest_descriptor;
      }

      public com.metasoft.flying.node.FlightProto.PvpSearchRequest getDefaultInstanceForType() {
        return com.metasoft.flying.node.FlightProto.PvpSearchRequest.getDefaultInstance();
      }

      public com.metasoft.flying.node.FlightProto.PvpSearchRequest build() {
        com.metasoft.flying.node.FlightProto.PvpSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.metasoft.flying.node.FlightProto.PvpSearchRequest buildPartial() {
        com.metasoft.flying.node.FlightProto.PvpSearchRequest result = new com.metasoft.flying.node.FlightProto.PvpSearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gold_ = gold_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.metasoft.flying.node.FlightProto.PvpSearchRequest) {
          return mergeFrom((com.metasoft.flying.node.FlightProto.PvpSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.metasoft.flying.node.FlightProto.PvpSearchRequest other) {
        if (other == com.metasoft.flying.node.FlightProto.PvpSearchRequest.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasGold()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.metasoft.flying.node.FlightProto.PvpSearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.metasoft.flying.node.FlightProto.PvpSearchRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 uid = 1;
      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // required int32 gold = 2;
      private int gold_ ;
      /**
       * <code>required int32 gold = 2;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 gold = 2;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>required int32 gold = 2;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000002;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gold = 2;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gold_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.metasoft.node.PvpSearchRequest)
    }

    static {
      defaultInstance = new PvpSearchRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.metasoft.node.PvpSearchRequest)
  }

  public interface PvpSearchResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool ok = 1 [default = false];
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    boolean hasOk();
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    boolean getOk();

    // optional string msg = 2;
    /**
     * <code>optional string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    // required int64 uid = 3;
    /**
     * <code>required int64 uid = 3;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 3;</code>
     */
    long getUid();
  }
  /**
   * Protobuf type {@code com.metasoft.node.PvpSearchResponse}
   */
  public static final class PvpSearchResponse extends
      com.google.protobuf.GeneratedMessage
      implements PvpSearchResponseOrBuilder {
    // Use PvpSearchResponse.newBuilder() to construct.
    private PvpSearchResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PvpSearchResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PvpSearchResponse defaultInstance;
    public static PvpSearchResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PvpSearchResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PvpSearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ok_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              uid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.metasoft.flying.node.FlightProto.PvpSearchResponse.class, com.metasoft.flying.node.FlightProto.PvpSearchResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PvpSearchResponse> PARSER =
        new com.google.protobuf.AbstractParser<PvpSearchResponse>() {
      public PvpSearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PvpSearchResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PvpSearchResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool ok = 1 [default = false];
    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    public boolean hasOk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    public boolean getOk() {
      return ok_;
    }

    // optional string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 uid = 3;
    public static final int UID_FIELD_NUMBER = 3;
    private long uid_;
    /**
     * <code>required int64 uid = 3;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 uid = 3;</code>
     */
    public long getUid() {
      return uid_;
    }

    private void initFields() {
      ok_ = false;
      msg_ = "";
      uid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, uid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, uid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.metasoft.flying.node.FlightProto.PvpSearchResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.metasoft.node.PvpSearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.metasoft.flying.node.FlightProto.PvpSearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.metasoft.flying.node.FlightProto.PvpSearchResponse.class, com.metasoft.flying.node.FlightProto.PvpSearchResponse.Builder.class);
      }

      // Construct using com.metasoft.flying.node.FlightProto.PvpSearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ok_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpSearchResponse_descriptor;
      }

      public com.metasoft.flying.node.FlightProto.PvpSearchResponse getDefaultInstanceForType() {
        return com.metasoft.flying.node.FlightProto.PvpSearchResponse.getDefaultInstance();
      }

      public com.metasoft.flying.node.FlightProto.PvpSearchResponse build() {
        com.metasoft.flying.node.FlightProto.PvpSearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.metasoft.flying.node.FlightProto.PvpSearchResponse buildPartial() {
        com.metasoft.flying.node.FlightProto.PvpSearchResponse result = new com.metasoft.flying.node.FlightProto.PvpSearchResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ok_ = ok_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uid_ = uid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.metasoft.flying.node.FlightProto.PvpSearchResponse) {
          return mergeFrom((com.metasoft.flying.node.FlightProto.PvpSearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.metasoft.flying.node.FlightProto.PvpSearchResponse other) {
        if (other == com.metasoft.flying.node.FlightProto.PvpSearchResponse.getDefaultInstance()) return this;
        if (other.hasOk()) {
          setOk(other.getOk());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.metasoft.flying.node.FlightProto.PvpSearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.metasoft.flying.node.FlightProto.PvpSearchResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool ok = 1 [default = false];
      private boolean ok_ ;
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public Builder setOk(boolean value) {
        bitField0_ |= 0x00000001;
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public Builder clearOk() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ok_ = false;
        onChanged();
        return this;
      }

      // optional string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // required int64 uid = 3;
      private long uid_ ;
      /**
       * <code>required int64 uid = 3;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 uid = 3;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 3;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000004;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 3;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.metasoft.node.PvpSearchResponse)
    }

    static {
      defaultInstance = new PvpSearchResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.metasoft.node.PvpSearchResponse)
  }

  public interface PvpBeginRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int64 uidSeq = 1;
    /**
     * <code>repeated int64 uidSeq = 1;</code>
     */
    java.util.List<java.lang.Long> getUidSeqList();
    /**
     * <code>repeated int64 uidSeq = 1;</code>
     */
    int getUidSeqCount();
    /**
     * <code>repeated int64 uidSeq = 1;</code>
     */
    long getUidSeq(int index);

    // required int32 gold = 2;
    /**
     * <code>required int32 gold = 2;</code>
     */
    boolean hasGold();
    /**
     * <code>required int32 gold = 2;</code>
     */
    int getGold();
  }
  /**
   * Protobuf type {@code com.metasoft.node.PvpBeginRequest}
   */
  public static final class PvpBeginRequest extends
      com.google.protobuf.GeneratedMessage
      implements PvpBeginRequestOrBuilder {
    // Use PvpBeginRequest.newBuilder() to construct.
    private PvpBeginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PvpBeginRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PvpBeginRequest defaultInstance;
    public static PvpBeginRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PvpBeginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PvpBeginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                uidSeq_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              uidSeq_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                uidSeq_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                uidSeq_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              gold_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          uidSeq_ = java.util.Collections.unmodifiableList(uidSeq_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpBeginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpBeginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.metasoft.flying.node.FlightProto.PvpBeginRequest.class, com.metasoft.flying.node.FlightProto.PvpBeginRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PvpBeginRequest> PARSER =
        new com.google.protobuf.AbstractParser<PvpBeginRequest>() {
      public PvpBeginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PvpBeginRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PvpBeginRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int64 uidSeq = 1;
    public static final int UIDSEQ_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> uidSeq_;
    /**
     * <code>repeated int64 uidSeq = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getUidSeqList() {
      return uidSeq_;
    }
    /**
     * <code>repeated int64 uidSeq = 1;</code>
     */
    public int getUidSeqCount() {
      return uidSeq_.size();
    }
    /**
     * <code>repeated int64 uidSeq = 1;</code>
     */
    public long getUidSeq(int index) {
      return uidSeq_.get(index);
    }

    // required int32 gold = 2;
    public static final int GOLD_FIELD_NUMBER = 2;
    private int gold_;
    /**
     * <code>required int32 gold = 2;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 gold = 2;</code>
     */
    public int getGold() {
      return gold_;
    }

    private void initFields() {
      uidSeq_ = java.util.Collections.emptyList();
      gold_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < uidSeq_.size(); i++) {
        output.writeInt64(1, uidSeq_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, gold_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < uidSeq_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(uidSeq_.get(i));
        }
        size += dataSize;
        size += 1 * getUidSeqList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gold_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpBeginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.metasoft.flying.node.FlightProto.PvpBeginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.metasoft.node.PvpBeginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.metasoft.flying.node.FlightProto.PvpBeginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpBeginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpBeginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.metasoft.flying.node.FlightProto.PvpBeginRequest.class, com.metasoft.flying.node.FlightProto.PvpBeginRequest.Builder.class);
      }

      // Construct using com.metasoft.flying.node.FlightProto.PvpBeginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uidSeq_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpBeginRequest_descriptor;
      }

      public com.metasoft.flying.node.FlightProto.PvpBeginRequest getDefaultInstanceForType() {
        return com.metasoft.flying.node.FlightProto.PvpBeginRequest.getDefaultInstance();
      }

      public com.metasoft.flying.node.FlightProto.PvpBeginRequest build() {
        com.metasoft.flying.node.FlightProto.PvpBeginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.metasoft.flying.node.FlightProto.PvpBeginRequest buildPartial() {
        com.metasoft.flying.node.FlightProto.PvpBeginRequest result = new com.metasoft.flying.node.FlightProto.PvpBeginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          uidSeq_ = java.util.Collections.unmodifiableList(uidSeq_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uidSeq_ = uidSeq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gold_ = gold_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.metasoft.flying.node.FlightProto.PvpBeginRequest) {
          return mergeFrom((com.metasoft.flying.node.FlightProto.PvpBeginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.metasoft.flying.node.FlightProto.PvpBeginRequest other) {
        if (other == com.metasoft.flying.node.FlightProto.PvpBeginRequest.getDefaultInstance()) return this;
        if (!other.uidSeq_.isEmpty()) {
          if (uidSeq_.isEmpty()) {
            uidSeq_ = other.uidSeq_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUidSeqIsMutable();
            uidSeq_.addAll(other.uidSeq_);
          }
          onChanged();
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGold()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.metasoft.flying.node.FlightProto.PvpBeginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.metasoft.flying.node.FlightProto.PvpBeginRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 uidSeq = 1;
      private java.util.List<java.lang.Long> uidSeq_ = java.util.Collections.emptyList();
      private void ensureUidSeqIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          uidSeq_ = new java.util.ArrayList<java.lang.Long>(uidSeq_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 uidSeq = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getUidSeqList() {
        return java.util.Collections.unmodifiableList(uidSeq_);
      }
      /**
       * <code>repeated int64 uidSeq = 1;</code>
       */
      public int getUidSeqCount() {
        return uidSeq_.size();
      }
      /**
       * <code>repeated int64 uidSeq = 1;</code>
       */
      public long getUidSeq(int index) {
        return uidSeq_.get(index);
      }
      /**
       * <code>repeated int64 uidSeq = 1;</code>
       */
      public Builder setUidSeq(
          int index, long value) {
        ensureUidSeqIsMutable();
        uidSeq_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 uidSeq = 1;</code>
       */
      public Builder addUidSeq(long value) {
        ensureUidSeqIsMutable();
        uidSeq_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 uidSeq = 1;</code>
       */
      public Builder addAllUidSeq(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureUidSeqIsMutable();
        super.addAll(values, uidSeq_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 uidSeq = 1;</code>
       */
      public Builder clearUidSeq() {
        uidSeq_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // required int32 gold = 2;
      private int gold_ ;
      /**
       * <code>required int32 gold = 2;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 gold = 2;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>required int32 gold = 2;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000002;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gold = 2;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gold_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.metasoft.node.PvpBeginRequest)
    }

    static {
      defaultInstance = new PvpBeginRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.metasoft.node.PvpBeginRequest)
  }

  public interface PvpResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool ok = 1 [default = false];
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    boolean hasOk();
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    boolean getOk();

    // optional string msg = 2;
    /**
     * <code>optional string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code com.metasoft.node.PvpResponse}
   */
  public static final class PvpResponse extends
      com.google.protobuf.GeneratedMessage
      implements PvpResponseOrBuilder {
    // Use PvpResponse.newBuilder() to construct.
    private PvpResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PvpResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PvpResponse defaultInstance;
    public static PvpResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PvpResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PvpResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ok_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.metasoft.flying.node.FlightProto.PvpResponse.class, com.metasoft.flying.node.FlightProto.PvpResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PvpResponse> PARSER =
        new com.google.protobuf.AbstractParser<PvpResponse>() {
      public PvpResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PvpResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PvpResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool ok = 1 [default = false];
    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    public boolean hasOk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool ok = 1 [default = false];</code>
     */
    public boolean getOk() {
      return ok_;
    }

    // optional string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ok_ = false;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.FlightProto.PvpResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.metasoft.flying.node.FlightProto.PvpResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.metasoft.node.PvpResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.metasoft.flying.node.FlightProto.PvpResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.metasoft.flying.node.FlightProto.PvpResponse.class, com.metasoft.flying.node.FlightProto.PvpResponse.Builder.class);
      }

      // Construct using com.metasoft.flying.node.FlightProto.PvpResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ok_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.metasoft.flying.node.FlightProto.internal_static_com_metasoft_node_PvpResponse_descriptor;
      }

      public com.metasoft.flying.node.FlightProto.PvpResponse getDefaultInstanceForType() {
        return com.metasoft.flying.node.FlightProto.PvpResponse.getDefaultInstance();
      }

      public com.metasoft.flying.node.FlightProto.PvpResponse build() {
        com.metasoft.flying.node.FlightProto.PvpResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.metasoft.flying.node.FlightProto.PvpResponse buildPartial() {
        com.metasoft.flying.node.FlightProto.PvpResponse result = new com.metasoft.flying.node.FlightProto.PvpResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ok_ = ok_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.metasoft.flying.node.FlightProto.PvpResponse) {
          return mergeFrom((com.metasoft.flying.node.FlightProto.PvpResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.metasoft.flying.node.FlightProto.PvpResponse other) {
        if (other == com.metasoft.flying.node.FlightProto.PvpResponse.getDefaultInstance()) return this;
        if (other.hasOk()) {
          setOk(other.getOk());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.metasoft.flying.node.FlightProto.PvpResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.metasoft.flying.node.FlightProto.PvpResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool ok = 1 [default = false];
      private boolean ok_ ;
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public Builder setOk(boolean value) {
        bitField0_ |= 0x00000001;
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ok = 1 [default = false];</code>
       */
      public Builder clearOk() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ok_ = false;
        onChanged();
        return this;
      }

      // optional string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.metasoft.node.PvpResponse)
    }

    static {
      defaultInstance = new PvpResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.metasoft.node.PvpResponse)
  }

  /**
   * Protobuf service {@code com.metasoft.node.PvpSearchService}
   */
  public static abstract class PvpSearchService
      implements com.google.protobuf.Service {
    protected PvpSearchService() {}

    public interface Interface {
      /**
       * <code>rpc search(.com.metasoft.node.PvpSearchRequest) returns (.com.metasoft.node.PvpSearchResponse);</code>
       */
      public abstract void search(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpSearchRequest request,
          com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpSearchResponse> done);

      /**
       * <code>rpc begin(.com.metasoft.node.PvpBeginRequest) returns (.com.metasoft.node.PvpResponse);</code>
       */
      public abstract void begin(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpBeginRequest request,
          com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PvpSearchService() {
        @java.lang.Override
        public  void search(
            com.google.protobuf.RpcController controller,
            com.metasoft.flying.node.FlightProto.PvpSearchRequest request,
            com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpSearchResponse> done) {
          impl.search(controller, request, done);
        }

        @java.lang.Override
        public  void begin(
            com.google.protobuf.RpcController controller,
            com.metasoft.flying.node.FlightProto.PvpBeginRequest request,
            com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpResponse> done) {
          impl.begin(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.search(controller, (com.metasoft.flying.node.FlightProto.PvpSearchRequest)request);
            case 1:
              return impl.begin(controller, (com.metasoft.flying.node.FlightProto.PvpBeginRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.metasoft.flying.node.FlightProto.PvpSearchRequest.getDefaultInstance();
            case 1:
              return com.metasoft.flying.node.FlightProto.PvpBeginRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.metasoft.flying.node.FlightProto.PvpSearchResponse.getDefaultInstance();
            case 1:
              return com.metasoft.flying.node.FlightProto.PvpResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc search(.com.metasoft.node.PvpSearchRequest) returns (.com.metasoft.node.PvpSearchResponse);</code>
     */
    public abstract void search(
        com.google.protobuf.RpcController controller,
        com.metasoft.flying.node.FlightProto.PvpSearchRequest request,
        com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpSearchResponse> done);

    /**
     * <code>rpc begin(.com.metasoft.node.PvpBeginRequest) returns (.com.metasoft.node.PvpResponse);</code>
     */
    public abstract void begin(
        com.google.protobuf.RpcController controller,
        com.metasoft.flying.node.FlightProto.PvpBeginRequest request,
        com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.metasoft.flying.node.FlightProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.search(controller, (com.metasoft.flying.node.FlightProto.PvpSearchRequest)request,
            com.google.protobuf.RpcUtil.<com.metasoft.flying.node.FlightProto.PvpSearchResponse>specializeCallback(
              done));
          return;
        case 1:
          this.begin(controller, (com.metasoft.flying.node.FlightProto.PvpBeginRequest)request,
            com.google.protobuf.RpcUtil.<com.metasoft.flying.node.FlightProto.PvpResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.metasoft.flying.node.FlightProto.PvpSearchRequest.getDefaultInstance();
        case 1:
          return com.metasoft.flying.node.FlightProto.PvpBeginRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.metasoft.flying.node.FlightProto.PvpSearchResponse.getDefaultInstance();
        case 1:
          return com.metasoft.flying.node.FlightProto.PvpResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.metasoft.flying.node.FlightProto.PvpSearchService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void search(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpSearchRequest request,
          com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpSearchResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.metasoft.flying.node.FlightProto.PvpSearchResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.metasoft.flying.node.FlightProto.PvpSearchResponse.class,
            com.metasoft.flying.node.FlightProto.PvpSearchResponse.getDefaultInstance()));
      }

      public  void begin(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpBeginRequest request,
          com.google.protobuf.RpcCallback<com.metasoft.flying.node.FlightProto.PvpResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.metasoft.flying.node.FlightProto.PvpResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.metasoft.flying.node.FlightProto.PvpResponse.class,
            com.metasoft.flying.node.FlightProto.PvpResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.metasoft.flying.node.FlightProto.PvpSearchResponse search(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpSearchRequest request)
          throws com.google.protobuf.ServiceException;

      public com.metasoft.flying.node.FlightProto.PvpResponse begin(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpBeginRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.metasoft.flying.node.FlightProto.PvpSearchResponse search(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpSearchRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.metasoft.flying.node.FlightProto.PvpSearchResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.metasoft.flying.node.FlightProto.PvpSearchResponse.getDefaultInstance());
      }


      public com.metasoft.flying.node.FlightProto.PvpResponse begin(
          com.google.protobuf.RpcController controller,
          com.metasoft.flying.node.FlightProto.PvpBeginRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.metasoft.flying.node.FlightProto.PvpResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.metasoft.flying.node.FlightProto.PvpResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.metasoft.node.PvpSearchService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_metasoft_node_PvpSearchRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_metasoft_node_PvpSearchRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_metasoft_node_PvpSearchResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_metasoft_node_PvpSearchResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_metasoft_node_PvpBeginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_metasoft_node_PvpBeginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_metasoft_node_PvpResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_metasoft_node_PvpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020rpc/flight.proto\022\021com.metasoft.node\"-\n" +
      "\020PvpSearchRequest\022\013\n\003uid\030\001 \002(\003\022\014\n\004gold\030\002" +
      " \002(\005\"@\n\021PvpSearchResponse\022\021\n\002ok\030\001 \001(\010:\005f" +
      "alse\022\013\n\003msg\030\002 \001(\t\022\013\n\003uid\030\003 \002(\003\"/\n\017PvpBeg" +
      "inRequest\022\016\n\006uidSeq\030\001 \003(\003\022\014\n\004gold\030\002 \002(\005\"" +
      "-\n\013PvpResponse\022\021\n\002ok\030\001 \001(\010:\005false\022\013\n\003msg" +
      "\030\002 \001(\t2\264\001\n\020PvpSearchService\022S\n\006search\022#." +
      "com.metasoft.node.PvpSearchRequest\032$.com" +
      ".metasoft.node.PvpSearchResponse\022K\n\005begi" +
      "n\022\".com.metasoft.node.PvpBeginRequest\032\036.",
      "com.metasoft.node.PvpResponseB0\n\030com.met" +
      "asoft.flying.nodeB\013FlightProto\200\001\001\210\001\001\220\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_metasoft_node_PvpSearchRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_metasoft_node_PvpSearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_metasoft_node_PvpSearchRequest_descriptor,
              new java.lang.String[] { "Uid", "Gold", });
          internal_static_com_metasoft_node_PvpSearchResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_metasoft_node_PvpSearchResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_metasoft_node_PvpSearchResponse_descriptor,
              new java.lang.String[] { "Ok", "Msg", "Uid", });
          internal_static_com_metasoft_node_PvpBeginRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_metasoft_node_PvpBeginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_metasoft_node_PvpBeginRequest_descriptor,
              new java.lang.String[] { "UidSeq", "Gold", });
          internal_static_com_metasoft_node_PvpResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_metasoft_node_PvpResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_metasoft_node_PvpResponse_descriptor,
              new java.lang.String[] { "Ok", "Msg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
