// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcMsg.proto

package com.metasoft.flying.node;

public final class RpcProto {
  private RpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.qianxun.model.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 1;</code>
     */
    REQUEST(0, 1),
    /**
     * <code>RESPONSE = 2;</code>
     */
    RESPONSE(1, 2),
    /**
     * <code>ERROR = 3;</code>
     *
     * <pre>
     * not used
     * </pre>
     */
    ERROR(2, 3),
    ;

    /**
     * <code>REQUEST = 1;</code>
     */
    public static final int REQUEST_VALUE = 1;
    /**
     * <code>RESPONSE = 2;</code>
     */
    public static final int RESPONSE_VALUE = 2;
    /**
     * <code>ERROR = 3;</code>
     *
     * <pre>
     * not used
     * </pre>
     */
    public static final int ERROR_VALUE = 3;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 1: return REQUEST;
        case 2: return RESPONSE;
        case 3: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.metasoft.flying.node.RpcProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.qianxun.model.MessageType)
  }

  /**
   * Protobuf enum {@code com.qianxun.model.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_ERROR = 0;</code>
     */
    NO_ERROR(0, 0),
    /**
     * <code>WRONG_PROTO = 1;</code>
     */
    WRONG_PROTO(1, 1),
    /**
     * <code>NO_SERVICE = 2;</code>
     */
    NO_SERVICE(2, 2),
    /**
     * <code>NO_METHOD = 3;</code>
     */
    NO_METHOD(3, 3),
    /**
     * <code>INVALID_REQUEST = 4;</code>
     */
    INVALID_REQUEST(4, 4),
    /**
     * <code>INVALID_RESPONSE = 5;</code>
     */
    INVALID_RESPONSE(5, 5),
    /**
     * <code>TIMEOUT = 6;</code>
     */
    TIMEOUT(6, 6),
    ;

    /**
     * <code>NO_ERROR = 0;</code>
     */
    public static final int NO_ERROR_VALUE = 0;
    /**
     * <code>WRONG_PROTO = 1;</code>
     */
    public static final int WRONG_PROTO_VALUE = 1;
    /**
     * <code>NO_SERVICE = 2;</code>
     */
    public static final int NO_SERVICE_VALUE = 2;
    /**
     * <code>NO_METHOD = 3;</code>
     */
    public static final int NO_METHOD_VALUE = 3;
    /**
     * <code>INVALID_REQUEST = 4;</code>
     */
    public static final int INVALID_REQUEST_VALUE = 4;
    /**
     * <code>INVALID_RESPONSE = 5;</code>
     */
    public static final int INVALID_RESPONSE_VALUE = 5;
    /**
     * <code>TIMEOUT = 6;</code>
     */
    public static final int TIMEOUT_VALUE = 6;


    public final int getNumber() { return value; }

    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 0: return NO_ERROR;
        case 1: return WRONG_PROTO;
        case 2: return NO_SERVICE;
        case 3: return NO_METHOD;
        case 4: return INVALID_REQUEST;
        case 5: return INVALID_RESPONSE;
        case 6: return TIMEOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.metasoft.flying.node.RpcProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.qianxun.model.ErrorCode)
  }

  public interface RpcMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.qianxun.model.MessageType type = 1;
    /**
     * <code>required .com.qianxun.model.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.qianxun.model.MessageType type = 1;</code>
     */
    com.metasoft.flying.node.RpcProto.MessageType getType();

    // required fixed64 id = 2;
    /**
     * <code>required fixed64 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required fixed64 id = 2;</code>
     */
    long getId();

    // optional string service = 3;
    /**
     * <code>optional string service = 3;</code>
     */
    boolean hasService();
    /**
     * <code>optional string service = 3;</code>
     */
    java.lang.String getService();
    /**
     * <code>optional string service = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceBytes();

    // optional string method = 4;
    /**
     * <code>optional string method = 4;</code>
     */
    boolean hasMethod();
    /**
     * <code>optional string method = 4;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string method = 4;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    // optional bytes request = 5;
    /**
     * <code>optional bytes request = 5;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional bytes request = 5;</code>
     */
    com.google.protobuf.ByteString getRequest();

    // optional bytes response = 6;
    /**
     * <code>optional bytes response = 6;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional bytes response = 6;</code>
     */
    com.google.protobuf.ByteString getResponse();

    // optional .com.qianxun.model.ErrorCode error = 7;
    /**
     * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
     */
    boolean hasError();
    /**
     * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
     */
    com.metasoft.flying.node.RpcProto.ErrorCode getError();
  }
  /**
   * Protobuf type {@code com.qianxun.model.RpcMessage}
   */
  public static final class RpcMessage extends
      com.google.protobuf.GeneratedMessage
      implements RpcMessageOrBuilder {
    // Use RpcMessage.newBuilder() to construct.
    private RpcMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcMessage defaultInstance;
    public static RpcMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RpcMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.metasoft.flying.node.RpcProto.MessageType value = com.metasoft.flying.node.RpcProto.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              id_ = input.readFixed64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              service_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              method_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              request_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              response_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.metasoft.flying.node.RpcProto.ErrorCode value = com.metasoft.flying.node.RpcProto.ErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                error_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.metasoft.flying.node.RpcProto.internal_static_com_qianxun_model_RpcMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.metasoft.flying.node.RpcProto.internal_static_com_qianxun_model_RpcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.metasoft.flying.node.RpcProto.RpcMessage.class, com.metasoft.flying.node.RpcProto.RpcMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcMessage> PARSER =
        new com.google.protobuf.AbstractParser<RpcMessage>() {
      public RpcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.qianxun.model.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.metasoft.flying.node.RpcProto.MessageType type_;
    /**
     * <code>required .com.qianxun.model.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.qianxun.model.MessageType type = 1;</code>
     */
    public com.metasoft.flying.node.RpcProto.MessageType getType() {
      return type_;
    }

    // required fixed64 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>required fixed64 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    // optional string service = 3;
    public static final int SERVICE_FIELD_NUMBER = 3;
    private java.lang.Object service_;
    /**
     * <code>optional string service = 3;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string service = 3;</code>
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          service_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string method = 4;
    public static final int METHOD_FIELD_NUMBER = 4;
    private java.lang.Object method_;
    /**
     * <code>optional string method = 4;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string method = 4;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes request = 5;
    public static final int REQUEST_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString request_;
    /**
     * <code>optional bytes request = 5;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes request = 5;</code>
     */
    public com.google.protobuf.ByteString getRequest() {
      return request_;
    }

    // optional bytes response = 6;
    public static final int RESPONSE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString response_;
    /**
     * <code>optional bytes response = 6;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes response = 6;</code>
     */
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    // optional .com.qianxun.model.ErrorCode error = 7;
    public static final int ERROR_FIELD_NUMBER = 7;
    private com.metasoft.flying.node.RpcProto.ErrorCode error_;
    /**
     * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
     */
    public com.metasoft.flying.node.RpcProto.ErrorCode getError() {
      return error_;
    }

    private void initFields() {
      type_ = com.metasoft.flying.node.RpcProto.MessageType.REQUEST;
      id_ = 0L;
      service_ = "";
      method_ = "";
      request_ = com.google.protobuf.ByteString.EMPTY;
      response_ = com.google.protobuf.ByteString.EMPTY;
      error_ = com.metasoft.flying.node.RpcProto.ErrorCode.NO_ERROR;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServiceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMethodBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, request_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, response_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, error_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServiceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMethodBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, request_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, response_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, error_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.metasoft.flying.node.RpcProto.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.metasoft.flying.node.RpcProto.RpcMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qianxun.model.RpcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.metasoft.flying.node.RpcProto.RpcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.metasoft.flying.node.RpcProto.internal_static_com_qianxun_model_RpcMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.metasoft.flying.node.RpcProto.internal_static_com_qianxun_model_RpcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.metasoft.flying.node.RpcProto.RpcMessage.class, com.metasoft.flying.node.RpcProto.RpcMessage.Builder.class);
      }

      // Construct using com.metasoft.flying.node.RpcProto.RpcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.metasoft.flying.node.RpcProto.MessageType.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        service_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        request_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        response_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        error_ = com.metasoft.flying.node.RpcProto.ErrorCode.NO_ERROR;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.metasoft.flying.node.RpcProto.internal_static_com_qianxun_model_RpcMessage_descriptor;
      }

      public com.metasoft.flying.node.RpcProto.RpcMessage getDefaultInstanceForType() {
        return com.metasoft.flying.node.RpcProto.RpcMessage.getDefaultInstance();
      }

      public com.metasoft.flying.node.RpcProto.RpcMessage build() {
        com.metasoft.flying.node.RpcProto.RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.metasoft.flying.node.RpcProto.RpcMessage buildPartial() {
        com.metasoft.flying.node.RpcProto.RpcMessage result = new com.metasoft.flying.node.RpcProto.RpcMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.service_ = service_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.request_ = request_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.response_ = response_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.metasoft.flying.node.RpcProto.RpcMessage) {
          return mergeFrom((com.metasoft.flying.node.RpcProto.RpcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.metasoft.flying.node.RpcProto.RpcMessage other) {
        if (other == com.metasoft.flying.node.RpcProto.RpcMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasService()) {
          bitField0_ |= 0x00000004;
          service_ = other.service_;
          onChanged();
        }
        if (other.hasMethod()) {
          bitField0_ |= 0x00000008;
          method_ = other.method_;
          onChanged();
        }
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.metasoft.flying.node.RpcProto.RpcMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.metasoft.flying.node.RpcProto.RpcMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.qianxun.model.MessageType type = 1;
      private com.metasoft.flying.node.RpcProto.MessageType type_ = com.metasoft.flying.node.RpcProto.MessageType.REQUEST;
      /**
       * <code>required .com.qianxun.model.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.qianxun.model.MessageType type = 1;</code>
       */
      public com.metasoft.flying.node.RpcProto.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .com.qianxun.model.MessageType type = 1;</code>
       */
      public Builder setType(com.metasoft.flying.node.RpcProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.qianxun.model.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.metasoft.flying.node.RpcProto.MessageType.REQUEST;
        onChanged();
        return this;
      }

      // required fixed64 id = 2;
      private long id_ ;
      /**
       * <code>required fixed64 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required fixed64 id = 2;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional string service = 3;
      private java.lang.Object service_ = "";
      /**
       * <code>optional string service = 3;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public java.lang.String getService() {
        java.lang.Object ref = service_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          service_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        java.lang.Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public Builder setService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000004);
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service = 3;</code>
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }

      // optional string method = 4;
      private java.lang.Object method_ = "";
      /**
       * <code>optional string method = 4;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string method = 4;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method = 4;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 4;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method = 4;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        method_ = value;
        onChanged();
        return this;
      }

      // optional bytes request = 5;
      private com.google.protobuf.ByteString request_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes request = 5;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes request = 5;</code>
       */
      public com.google.protobuf.ByteString getRequest() {
        return request_;
      }
      /**
       * <code>optional bytes request = 5;</code>
       */
      public Builder setRequest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        request_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes request = 5;</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000010);
        request_ = getDefaultInstance().getRequest();
        onChanged();
        return this;
      }

      // optional bytes response = 6;
      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response = 6;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes response = 6;</code>
       */
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>optional bytes response = 6;</code>
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response = 6;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000020);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }

      // optional .com.qianxun.model.ErrorCode error = 7;
      private com.metasoft.flying.node.RpcProto.ErrorCode error_ = com.metasoft.flying.node.RpcProto.ErrorCode.NO_ERROR;
      /**
       * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
       */
      public com.metasoft.flying.node.RpcProto.ErrorCode getError() {
        return error_;
      }
      /**
       * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
       */
      public Builder setError(com.metasoft.flying.node.RpcProto.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.qianxun.model.ErrorCode error = 7;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000040);
        error_ = com.metasoft.flying.node.RpcProto.ErrorCode.NO_ERROR;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qianxun.model.RpcMessage)
    }

    static {
      defaultInstance = new RpcMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qianxun.model.RpcMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qianxun_model_RpcMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qianxun_model_RpcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014rpcMsg.proto\022\021com.qianxun.model\"\267\001\n\nRp" +
      "cMessage\022,\n\004type\030\001 \002(\0162\036.com.qianxun.mod" +
      "el.MessageType\022\n\n\002id\030\002 \002(\006\022\017\n\007service\030\003 " +
      "\001(\t\022\016\n\006method\030\004 \001(\t\022\017\n\007request\030\005 \001(\014\022\020\n\010" +
      "response\030\006 \001(\014\022+\n\005error\030\007 \001(\0162\034.com.qian" +
      "xun.model.ErrorCode*3\n\013MessageType\022\013\n\007RE" +
      "QUEST\020\001\022\014\n\010RESPONSE\020\002\022\t\n\005ERROR\020\003*\201\001\n\tErr" +
      "orCode\022\014\n\010NO_ERROR\020\000\022\017\n\013WRONG_PROTO\020\001\022\016\n" +
      "\nNO_SERVICE\020\002\022\r\n\tNO_METHOD\020\003\022\023\n\017INVALID_" +
      "REQUEST\020\004\022\024\n\020INVALID_RESPONSE\020\005\022\013\n\007TIMEO",
      "UT\020\006B$\n\030com.metasoft.flying.nodeB\010RpcPro" +
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_qianxun_model_RpcMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_qianxun_model_RpcMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_qianxun_model_RpcMessage_descriptor,
              new java.lang.String[] { "Type", "Id", "Service", "Method", "Request", "Response", "Error", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
