---
spring:
  profiles: feign
  application.name: dummy-feign

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.254:${eureka.server.port}/eureka/
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
