spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

spring.datasource.url: jdbc:postgresql://yy/dadb
spring.datasource.username: postgres
spring.datasource.password:
spring.datasource.driver-class-name: org.postgresql.Driver

application.message: Hello Phil
init.db: true

server:
  port: 8082
  contextPath: /data-analysis
